/**
 * Flower Room monitoring manifest.
 *
 * Extracted from the canonical Grafana dashboard
 * `Infrastructure/iskra_stack/dashboards/flower_sector/flower_sector.json`
 * (panels 24-1658). Panel order follows the canonical grid layout; series
 * names, display names, units, soft bounds, colors, and line styles are taken
 * from the canonical `fieldConfig` defaults and overrides.
 *
 * The parity test maps every canonical panel/series/row onto this manifest and
 * rejects unknown additions.
 */
import type { MonitoringManifest } from './manifestTypes'

export const flowerManifest: MonitoringManifest = {
  room: 'Flower Room',
  sensorClusters: ['front', 'back'],
  panels: [
    {
      kind: 'table',
      id: 'flower-averages',
      title: 'Averages',
      columns: ['Sensor', 'Value'],
      rows: [
        'Dry Bulb Avg',
        'Wet Bulb Avg',
        'RH Avg',
        'VPD Avg',
        'CO2 Avg',
        'Pressure Avg',
        'Last Update',
      ],
      units: ['°C', '°C', '%', ' kPa', ' ppm', ' hPa', ' mm'],
      hasLastUpdate: true,
    },
    {
      kind: 'timeseries',
      id: 'flower-climate',
      title: 'Flower climate conditions',
      sources: ['sensor', 'climate'],
      families: ['temperature', 'rh', 'vpd'],
      defaults: { unit: 'celsius', softMin: 15 },
      series: [
        {
          name: 'dry_bulb_f',
          displayName: 'Dry Bulb (°C) - Front',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#e02b2b',},
        {
          name: 'wet_bulb_f',
          displayName: 'Wet Bulb (°C) - Front',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#23306e',},
        {
          name: 'rh_f',
          displayName: 'RH (%) - Front',
          unit: 'percent',
          axisPlacement: 'right',
          softMax: 100,
          decimals: 1,
          color: '#FADE2A',},
        {
          name: 'vpd_f',
          displayName: 'VPD (kPa) - Front',
          unit: 'kpa',
          axisPlacement: 'auto',
          decimals: 2,
          color: '#2f7fe0',
          lineWidth: 3,},
        {
          name: 'dry_bulb_b',
          displayName: 'Dry Bulb (°C) - Back',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#e02b2b',
        },
        {
          name: 'wet_bulb_b',
          displayName: 'Wet Bulb (°C) - Back',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#4169e1',
        },
        {
          name: 'rh_b',
          displayName: 'RH (%) - Back',
          unit: 'percent',
          axisPlacement: 'right',
          softMax: 100,
          decimals: 1,
          color: '#fade2a',},
        {
          name: 'vpd_b',
          displayName: 'VPD (kPa) - Back',
          unit: 'kpa',
          axisPlacement: 'auto',
          decimals: 2,
          color: '#2f7fe0',
          lineWidth: 3,},
        {
          name: 'Heating Setpoint - Main',
          displayName: 'Heating Setpoint - Main',
          unit: 'celsius',
          color: '#c257d6',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'VPD Setpoint - Main',
          displayName: 'VPD Setpoint - Main',
          unit: 'kpa',
          color: '#FADE2A',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'Cooling Setpoint - Main',
          displayName: 'Cooling Setpoint - Main',
          unit: 'celsius',
          color: '#57c4ad',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'heating_setpoint',
          displayName: 'Heating Setpoint',
          unit: 'celsius',
          color: '#ff6fb0',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'cooling_setpoint',
          displayName: 'Cooling Setpoint',
          unit: 'celsius',
          color: '#4fd1c5',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'vpd_setpoint',
          displayName: 'VPD Setpoint',
          unit: 'kpa',
          color: '#c0dd55',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
                {
          name: 'DAY Period Overlay',
          displayName: 'DAY Period Overlay',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'yellow',
        },
        {
          name: 'NIGHT Period Overlay',
          displayName: 'NIGHT Period Overlay',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'blue',
        },
      ],
    },
    {
      kind: 'table',
      id: 'flower-front',
      title: 'Front Cluster',
      columns: ['Sensor', 'Value'],
      rows: [
        'Dry Bulb',
        'Wet Bulb',
        'RH',
        'VPD',
        'CO2',
        'Pressure',
        'Secondary Temp',
        'Secondary RH',
        'Water Level',
        'Last Update',
      ],
      units: ['°C', '°C', '%', '%', ' kPa', ' ppm', ' hPa', ' mm'],
      hasLastUpdate: true,
    },
    {
      kind: 'table',
      id: 'flower-back',
      title: 'Back Cluster',
      columns: ['Sensor', 'Value'],
      rows: [
        'Dry Bulb',
        'Wet Bulb',
        'RH',
        'VPD',
        'CO2',
        'Pressure',
        'Secondary Temp',
        'Secondary RH',
        'Water Level',
        'Last Update',
      ],
      units: ['°C', '°C', '%', '%', ' kPa', ' ppm', ' hPa', ' mm'],
      hasLastUpdate: true,
    },
    {
      kind: 'timeseries',
      id: 'flower-systems',
      title: 'Flower atmosphere & equipment',
      sources: ['sensor', 'climate', 'light', 'device', 'pid'],
      families: ['pressure', 'device', 'light'],
      defaults: { unit: 'ppm' },
      series: [
        {
          name: 'co2_b',
          displayName: 'CO₂ - Back',
          unit: 'ppm',
          axisPlacement: 'auto',
        },
        {
          name: 'pressure_b',
          displayName: 'Pressure (hPa) - Back',
          unit: 'hpa',
          axisPlacement: 'right',
          softMin: 1012,
          softMax: 1014,
          decimals: 1,
        },
        {
          name: 'exhaust_fan - State',
          displayName: 'Exhaust Fan - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'gray',
        },
        {
          name: 'Midea Cube 50 pints - State',
          displayName: 'Dehumidifier - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'cyan',
        },
        {
          name: 'Heater Flower - State',
          displayName: 'Heater - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'red',
        },
        {
          name: 'light_1 - Duty Cycle',
          displayName: 'Light 1 - Duty Cycle',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'yellow',
          decimals: 1,
        },
        {
          name: 'light_2 - Duty Cycle',
          displayName: 'Light 2 - Duty Cycle',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'orange',
          decimals: 1,
        },
        {
          name: 'light_3 - Duty Cycle',
          displayName: 'Light 3 - Duty Cycle',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'purple',
          decimals: 1,
        },
        {
          name: 'Heater Flower - PID Output',
          displayName: 'Heater - PID Output',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'red',
          decimals: 1,
        },
        {
          name: 'light_1 - Intensity',
          displayName: 'Chilled Front - Intensity',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'yellow',
        },
        {
          name: 'light_2 - Intensity',
          displayName: 'Apache - Intensity',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'orange',
        },
        {
          name: 'light_3 - Intensity',
          displayName: 'Chilled Back - Intensity',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'purple',
        },
      ],
    },
    {
      kind: 'table',
      id: 'flower-statistics',
      title: 'Statistics - All Available Sensors',
      columns: ['Sensor', 'Min', 'Max', 'Average', 'Std Dev'],
      rows: [
        'Dry Bulb (°C) - Front',
        'Dry Bulb (°C) - Back',
        'Wet Bulb (°C) - Front',
        'Wet Bulb (°C) - Back',
        'RH (%) - Front',
        'RH (%) - Back',
        'VPD (kPa) - Front',
        'VPD (kPa) - Back',
        'CO2 (ppm) - Front',
        'CO2 (ppm) - Back',
        'Pressure (hPa) - Front',
        'Pressure (hPa) - Back',
        'Secondary Temp (°C) - Front',
        'Secondary Temp (°C) - Back',
        'Secondary RH (%) - Front',
        'Secondary RH (%) - Back',
        'Water Level (mm) - Front',
        'Water Level (mm) - Back',
      ],
      hasLastUpdate: false,
    },
  ],
}
