/**
 * Veg Room monitoring manifest.
 *
 * Extracted from the canonical Grafana dashboard
 * `Infrastructure/iskra_stack/dashboards/veg_sector/veg_sector.json`
 * (panels 24-1257). Panel order follows the canonical grid layout; series
 * names, display names, units, soft bounds, colors, and line styles are taken
 * from the canonical `fieldConfig` defaults and overrides.
 *
 * The parity test maps every canonical panel/series/row onto this manifest and
 * rejects unknown additions.
 */
import type { MonitoringManifest } from './manifestTypes'

export const vegManifest: MonitoringManifest = {
  room: 'Veg Room',
  sensorClusters: ['main'],
  panels: [
    {
      kind: 'table',
      id: 'veg-values',
      title: 'Sensor Values',
      columns: ['Data'],
      rows: [
        'Dry Bulb',
        'Wet Bulb',
        'RH',
        'VPD',
        'CO2',
        'Pressure',
        'Secondary Temp',
        'Secondary RH',
        'Water Level',
        'Last Update',
      ],
      units: ['°C', '°C', '%', '%', ' kPa', ' ppm', ' hPa', ' mm'],
      hasLastUpdate: true,
    },
    {
      kind: 'timeseries',
      id: 'veg-climate',
      title: 'Veg climate conditions',
      sources: ['sensor', 'climate'],
      families: ['temperature', 'rh', 'vpd'],
      defaults: { unit: 'celsius', softMin: 15 },
      series: [
        {
          name: 'dry_bulb_v',
          displayName: 'Dry Bulb (°C)',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#e02b2b',
        },
        {
          name: 'wet_bulb_v',
          displayName: 'Wet Bulb (°C)',
          unit: 'celsius',
          axisPlacement: 'auto',
          color: '#4169e1',
        },
        {
          name: 'rh_v',
          displayName: 'RH (%)',
          unit: 'percent',
          axisPlacement: 'right',
          softMax: 100,
          decimals: 1,
          color: '#fade2a',},
        {
          name: 'vpd_v',
          displayName: 'VPD (kPa)',
          unit: 'kpa',
          axisPlacement: 'auto',
          decimals: 2,
          color: '#2f7fe0',
          lineWidth: 3,},
        {
          name: 'Heating Setpoint - Main',
          displayName: 'Heating Setpoint',
          unit: 'celsius',
          color: 'dark-red',
          lineStyle: 'dot',
          lineWidth: 3,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'VPD Setpoint - Main',
          displayName: 'VPD Setpoint',
          unit: 'kpa',
          color: 'super-light-blue',
          lineStyle: 'dot',
          lineWidth: 3,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'Cooling Setpoint - Main',
          displayName: 'Cooling Setpoint',
          unit: 'celsius',
          color: 'dark-blue',
          lineStyle: 'dot',
          lineWidth: 3,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'heating_setpoint',
          displayName: 'Heating Setpoint',
          unit: 'celsius',
          color: '#ff6fb0',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'cooling_setpoint',
          displayName: 'Cooling Setpoint',
          unit: 'celsius',
          color: '#4fd1c5',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
        {
          name: 'vpd_setpoint',
          displayName: 'VPD Setpoint',
          unit: 'kpa',
          color: '#c0dd55',
          lineStyle: 'dot',
          lineWidth: 2,
          lineInterpolation: 'stepBefore',
        },
                {
          name: 'DAY Period Overlay',
          displayName: 'DAY Period Overlay',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'yellow',
        },
        {
          name: 'NIGHT Period Overlay',
          displayName: 'NIGHT Period Overlay',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'blue',
        },
      ],
    },
    {
      kind: 'timeseries',
      id: 'veg-systems',
      title: 'Veg atmosphere & equipment',
      sources: ['sensor', 'climate', 'light', 'device', 'pid'],
      families: ['pressure', 'device', 'light'],
      defaults: { unit: 'ppm' },
      series: [
        {
          name: 'pressure_v',
          displayName: 'Pressure (hPa)',
          unit: 'hpa',
          axisPlacement: 'right',
          decimals: 1,
        },
        {
          name: 'Exhaust 4 inches - State',
          displayName: 'Exhaust Fan - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'gray',
        },
        {
          name: 'light_1 - Intensity',
          displayName: 'Eyefinity Top - Intensity',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'yellow',
        },
        {
          name: 'light_2 - Intensity',
          displayName: 'Ridgetop Bottom Right - Intensity',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'orange',
        },
        {
          name: 'light_3 - Intensity',
          displayName: 'Ridgetop Bottom Left - Intensity',
          unit: 'percent',
          axisPlacement: 'hidden',
          softMin: 0,
          softMax: 100,
          color: 'purple',
        },
        {
          name: 'Ivation 35 pints - State',
          displayName: 'Dehumidifier - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'cyan',
        },
        {
          name: 'Heater Veg - State',
          displayName: 'Heater - State',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          drawStyle: 'bars',
          lineInterpolation: 'stepAfter',
          color: 'red',
        },
        {
          name: 'Heater Veg - PID Output',
          displayName: 'Heater - PID Output',
          unit: 'percent',
          axisPlacement: 'right',
          softMin: 0,
          softMax: 100,
          color: 'red',
          decimals: 1,
        },
      ],
    },
    {
      kind: 'table',
      id: 'veg-statistics',
      title: 'Statistics - All Available Sensors',
      columns: ['Sensor', 'Min', 'Max', 'Average', 'Std Dev'],
      rows: [
        'Dry Bulb (°C)',
        'Wet Bulb (°C)',
        'RH (%)',
        'VPD (kPa)',
        'CO2 (ppm)',
        'Pressure (hPa)',
        'Secondary Temp (°C)',
        'Secondary RH (%)',
        'Water Level (mm)',
      ],
      hasLastUpdate: false,
    },
  ],
}
