\set ON_ERROR_STOP on

DO $guard$
BEGIN
    IF current_database() IN ('cea_sensors', 'cea_sensors_test')
       OR current_database() !~ '^monitoring_test_[a-z0-9_]+$' THEN
        RAISE EXCEPTION 'monitoring fixtures require the monitoring_test_ database namespace';
    END IF;
END
$guard$;

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE monitoring_fixture_metadata (
    fixture_name TEXT PRIMARY KEY,
    fixture_version INTEGER NOT NULL CHECK (fixture_version > 0)
);

CREATE TABLE room (
    room_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE rack (
    rack_id INTEGER PRIMARY KEY,
    room_id INTEGER NOT NULL REFERENCES room(room_id),
    name TEXT NOT NULL,
    UNIQUE (room_id, name)
);

CREATE TABLE device (
    device_id INTEGER PRIMARY KEY,
    rack_id INTEGER REFERENCES rack(rack_id),
    name TEXT NOT NULL,
    type TEXT NOT NULL
);

CREATE TABLE sensor (
    sensor_id INTEGER PRIMARY KEY,
    device_id INTEGER NOT NULL REFERENCES device(device_id),
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    data_type TEXT NOT NULL,
    UNIQUE (device_id, name)
);

CREATE TABLE measurement (
    time TIMESTAMPTZ NOT NULL,
    sensor_id INTEGER NOT NULL REFERENCES sensor(sensor_id),
    value DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL DEFAULT 'ok',
    PRIMARY KEY (time, sensor_id)
);

SELECT create_hypertable(
    'measurement',
    by_range('time', INTERVAL '1 day'),
    if_not_exists => TRUE
);

CREATE TABLE effective_setpoints (
    timestamp TIMESTAMPTZ NOT NULL,
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    mode TEXT,
    device_name TEXT,
    effective_heating_setpoint DOUBLE PRECISION,
    effective_cooling_setpoint DOUBLE PRECISION,
    effective_humidity_setpoint DOUBLE PRECISION,
    effective_co2_setpoint DOUBLE PRECISION,
    effective_vpd_setpoint DOUBLE PRECISION,
    effective_light_intensity DOUBLE PRECISION
);

SELECT create_hypertable(
    'effective_setpoints',
    by_range('timestamp', INTERVAL '1 day'),
    if_not_exists => TRUE
);

CREATE TABLE automation_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL,
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    device_name TEXT NOT NULL,
    device_state INTEGER NOT NULL,
    device_mode TEXT NOT NULL,
    pid_output DOUBLE PRECISION,
    duty_cycle_percent DOUBLE PRECISION,
    control_reason TEXT
);

SELECT create_hypertable(
    'automation_state',
    by_range('timestamp', INTERVAL '1 day'),
    if_not_exists => TRUE
);

CREATE TABLE room_modes (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_constant BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE active_room_modes (
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    mode_id INTEGER NOT NULL REFERENCES room_modes(id),
    PRIMARY KEY (location, cluster)
);

CREATE TABLE mode_parameters (
    id INTEGER PRIMARY KEY,
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    mode_id INTEGER NOT NULL REFERENCES room_modes(id),
    day_start_time TIME NOT NULL,
    night_start_time TIME NOT NULL,
    light_ramp_up_minutes INTEGER NOT NULL,
    light_ramp_down_minutes INTEGER NOT NULL,
    UNIQUE (location, cluster, mode_id)
);

CREATE TABLE climate_periods (
    id INTEGER PRIMARY KEY,
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    mode_id INTEGER NOT NULL REFERENCES room_modes(id),
    name TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    ramp_minutes INTEGER NOT NULL,
    heating_setpoint DOUBLE PRECISION,
    cooling_setpoint DOUBLE PRECISION,
    vpd_setpoint DOUBLE PRECISION,
    co2_setpoint DOUBLE PRECISION
);

CREATE TABLE device_registry (
    device_id INTEGER PRIMARY KEY,
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    device_name TEXT NOT NULL,
    device_type TEXT NOT NULL,
    dimming_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (location, cluster, device_name)
);

CREATE TABLE light_target_intensity (
    device_id INTEGER NOT NULL REFERENCES device_registry(device_id),
    mode_id INTEGER NOT NULL REFERENCES room_modes(id),
    target_intensity DOUBLE PRECISION NOT NULL CHECK (target_intensity BETWEEN 0 AND 100),
    PRIMARY KEY (device_id, mode_id)
);

CREATE TABLE light_programs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER REFERENCES device_registry(device_id),
    location TEXT NOT NULL,
    cluster TEXT NOT NULL,
    mode_id INTEGER REFERENCES room_modes(id),
    name TEXT NOT NULL,
    program_type TEXT NOT NULL CHECK (program_type IN ('supplemental', 'override')),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    target_intensity DOUBLE PRECISION NOT NULL CHECK (target_intensity BETWEEN 0 AND 100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL
);

INSERT INTO monitoring_fixture_metadata (fixture_name, fixture_version)
VALUES ('grafana-replacement-veg-flower', 1);

INSERT INTO room (room_id, name)
VALUES
    (1, 'Flower Room'),
    (2, 'Veg Room');

INSERT INTO rack (rack_id, room_id, name)
VALUES
    (1, 1, 'flower-sensors'),
    (2, 2, 'veg-sensors');

INSERT INTO device (device_id, rack_id, name, type)
VALUES
    (1, 1, 'flower-back-node', 'sensor-node'),
    (2, 1, 'flower-front-node', 'sensor-node'),
    (3, 2, 'veg-main-node', 'sensor-node');

INSERT INTO sensor (sensor_id, device_id, name, unit, data_type)
VALUES
    (1, 1, 'dry_bulb_b', '°C', 'temperature'),
    (2, 1, 'rh_b', '%', 'humidity'),
    (3, 1, 'vpd_b', 'kPa', 'vpd'),
    (4, 2, 'dry_bulb_f', '°C', 'temperature'),
    (5, 3, 'dry_bulb_v', '°C', 'temperature'),
    (6, 3, 'co2_v', 'ppm', 'co2');

INSERT INTO measurement (time, sensor_id, value)
VALUES
    ('2026-01-01T00:00:00Z', 1, 20.0),
    ('2026-01-01T00:00:30Z', 1, 22.0),
    ('2026-01-01T00:00:59.500Z', 1, 28.0),
    ('2026-01-01T00:01:00Z', 1, 18.0),
    ('2026-01-01T01:00:00Z', 1, 24.0),
    ('2026-01-01T06:00:00Z', 1, 26.0),
    ('2026-01-07T23:59:59Z', 1, 21.0),
    ('2026-01-01T00:00:00Z', 2, 45.0),
    ('2026-01-01T00:00:30Z', 2, 75.0),
    ('2026-01-01T00:00:00Z', 3, 1.10),
    ('2026-01-01T00:00:00Z', 5, 23.5),
    ('2026-01-01T00:01:00Z', 5, 24.5),
    ('2026-01-01T00:00:00Z', 6, 800.0);

INSERT INTO effective_setpoints (
    timestamp,
    location,
    cluster,
    mode,
    device_name,
    effective_heating_setpoint,
    effective_cooling_setpoint,
    effective_humidity_setpoint,
    effective_co2_setpoint,
    effective_vpd_setpoint,
    effective_light_intensity
)
VALUES
    ('2026-01-01T00:00:00Z', 'Flower Room', 'main', 'DAY', NULL, 23.0, 27.0, 58.0, 1000.0, 1.20, NULL),
    ('2026-01-01T00:05:00Z', 'Flower Room', 'main', 'DAY', 'light_f_1', NULL, NULL, NULL, NULL, NULL, 80.0),
    ('2026-01-01T00:00:00Z', 'Veg Room', 'main', 'DAY', NULL, 22.0, 26.0, 62.0, 900.0, 1.00, NULL);

INSERT INTO automation_state (
    id,
    timestamp,
    location,
    cluster,
    device_name,
    device_state,
    device_mode,
    pid_output,
    duty_cycle_percent,
    control_reason
)
VALUES
    (1, '2026-01-01T00:00:00Z', 'Flower Room', 'main', 'heater_f_1', 1, 'auto', NULL, 100.0, 'below heating setpoint'),
    (2, '2026-01-01T00:01:00Z', 'Flower Room', 'main', 'heater_f_1', 1, 'auto', 0.75, 75.0, 'PID demand'),
    (3, '2026-01-01T00:00:00Z', 'Veg Room', 'main', 'fan_v_1', 0, 'scheduled', NULL, NULL, 'photoperiod off');

INSERT INTO room_modes (id, name, is_constant)
VALUES
    (1, 'veg', FALSE),
    (2, 'flower', FALSE),
    (3, 'drying', TRUE);

INSERT INTO active_room_modes (location, cluster, mode_id)
VALUES
    ('Flower Room', 'main', 2),
    ('Veg Room', 'main', 1);

INSERT INTO mode_parameters (
    id,
    location,
    cluster,
    mode_id,
    day_start_time,
    night_start_time,
    light_ramp_up_minutes,
    light_ramp_down_minutes
)
VALUES
    (1, 'Flower Room', 'main', 2, '20:00', '08:00', 30, 20),
    (2, 'Veg Room', 'main', 1, '06:00', '00:00', 15, 15);

INSERT INTO climate_periods (
    id,
    location,
    cluster,
    mode_id,
    name,
    start_time,
    end_time,
    ramp_minutes,
    heating_setpoint,
    cooling_setpoint,
    vpd_setpoint,
    co2_setpoint
)
VALUES
    (1, 'Flower Room', 'main', 2, 'day', '20:00', '06:00', 30, 23.0, 27.0, 1.20, 1000.0),
    (2, 'Flower Room', 'main', 2, 'pre-night', '06:00', '08:00', 20, 21.0, 25.0, 1.00, 800.0),
    (3, 'Veg Room', 'main', 1, 'day', '06:00', '00:00', 15, 22.0, 26.0, 1.00, 900.0);

INSERT INTO device_registry (
    device_id,
    location,
    cluster,
    device_name,
    device_type,
    dimming_enabled
)
VALUES
    (101, 'Flower Room', 'main', 'light_f_1', 'light', TRUE),
    (102, 'Flower Room', 'main', 'heater_f_1', 'heater', FALSE),
    (201, 'Veg Room', 'main', 'light_v_1', 'light', TRUE),
    (202, 'Veg Room', 'main', 'fan_v_1', 'fan', FALSE);

INSERT INTO light_target_intensity (device_id, mode_id, target_intensity)
VALUES
    (101, 2, 80.0),
    (201, 1, 65.0);

INSERT INTO light_programs (
    id,
    device_id,
    location,
    cluster,
    mode_id,
    name,
    program_type,
    start_time,
    end_time,
    target_intensity,
    enabled,
    priority,
    created_at
)
VALUES
    (1, 101, 'Flower Room', 'main', 2, 'low-priority override', 'override', '21:00', '22:00', 70.0, TRUE, 10, '2026-01-01T00:00:00Z'),
    (2, 101, 'Flower Room', 'main', 2, 'high-priority override', 'override', '21:00', '22:00', 90.0, TRUE, 20, '2026-01-01T00:01:00Z'),
    (3, NULL, 'Veg Room', 'main', 1, 'veg supplemental', 'supplemental', '00:00', '02:00', 25.0, TRUE, 5, '2026-01-01T00:00:00Z');

SELECT setval(pg_get_serial_sequence('automation_state', 'id'), 3, TRUE);
SELECT setval(pg_get_serial_sequence('light_programs', 'id'), 3, TRUE);
